apiVersion: apps/v1
kind: Deployment
metadata:
  name: natours-front
  namespace: natours
spec:
  replicas: 1
  selector:
    matchLabels:
      app: natours-front
  template:
    metadata:
      labels:
        app: natours-front
    spec:
      containers:
        - name: natours-front
          image: gucasassi/natours-front:1.0.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 80
